### ISSUE TITLE
Do not test a command validity after each line, use a trap

### ISSUE THREAD

**Issue by maxux** [Jumpscale/developer#10]
This kind of code should really be avoided.
```
error_handling() {
  EXITCODE=$?
  if [ ${EXITCODE} -ne 0 ]; then
    [...]
  fi
}

mkdir -p $DATADIR > /tmp/lastcommandoutput.txt 2>&1
valid
mkdir -p $CODEDIR/github/jumpscale > /tmp/lastcommandoutput.txt 2>&1
valid
mkdir -p $CFGDIR > /tmp/lastcommandoutput.txt 2>&1
valid
```

A better approach is to use a trap:
```
function () {
  EXITCODE=$?
  if [ ${EXITCODE} -ne 0 ]; then
    [...]
  fi
  exit $EXITCODE
}

trap error_handling ERR

mkdir -p $DATADIR > /tmp/lastcommandoutput.txt 2>&1
mkdir -p $CODEDIR/github/jumpscale > /tmp/lastcommandoutput.txt 2>&1
mkdir -p $CFGDIR > /tmp/lastcommandoutput.txt 2>&1
```

**Comment by despiegk** [comment]
i agree it looks much nicer but I see an issue

![image](https://cloud.githubusercontent.com/assets/6021844/25561854/55c94438-2d85-11e7-9b1e-87f8d4d99f3f.png)

geert wants to give an error message, that becomes difficult then

**Comment by maxux** [comment]
This is already ported on `refactor` branch:
Error handler is installed and theses custom errors are written like this:
https://github.com/Jumpscale/developer/blob/refactor/scripts/js_builder82_zerotier.sh#L74-L76

**Comment by rkhamis** [comment]
@maxux What's the status here?
