### ISSUE TITLE
Proper argument parsing for the docker creation scripts

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/developer#13]
the `scripts/js_builder82_zerotier.sh` and `scripts/g8os_grid_installer82.sh` scripts only check the number of arguments, this resulted in for example a `./js_builder82_zerotier.sh -h` to try to connect to the zerotier network with id `-h` instead of printing the help text.

**Comment by maxux** [comment]
This is fixed on the new incoming version :)
