### ISSUE TITLE
Support for more Linux distribution.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/developer#19]
Since the goal is to run jumpscale in a docker, the jsinit script should be compatible with the more distribution as possible so the host OS doesn't matter anymore.
The only difference is the package manager used. So if we could detect it and use the appropriate we could have a generic way to install on any system.

- apt
- pacman
- DNF (fedora)
- RPM

**Comment by ashraffouda** [comment]
I will add support for Fedora part

**Comment by xmonader** [comment]
It's working on archlinux + ubuntu + fedora

**Comment by zaibon** [comment]
Good enough for now.
