### ISSUE TITLE
Jumpscale 9 installation scripts should all have proper error handling

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/developer#28]
Each statement needs to be validated for its success.

**Comment by despiegk** [comment]
what does this mean?
what do we want

**Comment by rkhamis** [comment]
We should check that we always die on errors and we don't have a falsely successful installation

**Comment by xmonader** [comment]
Just checked with @maxux . Developer/js_builder_base9.sh uses `catcherror` function "relatively new" that sets trap on ERR to log/exit
