### ISSUE TITLE
the way how we deal with always die is GONE 

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/developer#41]
![image](https://user-images.githubusercontent.com/6021844/27000555-74786c42-4db5-11e7-8284-7e41ef55613e.png)

this cannot work, if any issue during js9 install it just stops,
the way how always die was done originally was much more safe

why has this been removed!!!

**Comment by despiegk** [comment]
we need to redo the way how the always die was implemented !!!
everything goes to the logfile and there is an always die

and this logfile is not visible on host which is also not cool

**Comment by despiegk** [comment]
this happens all over the place
this is a serious issue and needs to be fixed asap

**Comment by maxux** [comment]
On `jsenv-functions.sh`, this was re-introduced:
```
catcherror_handler() {
    if [ "${logfile}" != "" ]; then
        echo "[-] line $1: script error, backlog from ${logfile}:"
        cat ${logfile}
        exit 1
    fi

    echo "[-] line $1: script error, no logging file defined"
    exit 1
}

catcherror() {
    trap 'catcherror_handler $LINENO' ERR
}
```

This can be called for general purpuse but for more specific error handling, `command || errorhandler` needs to be used to have a proper output
