### ISSUE TITLE
Should js9_start.sh do a rm and start?

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/developer#45]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description

Does it make sense a method called start deleted the existing docker and makes a new one from the template?

I would suggest to change this behaviour to use docker start in case the container already exists. Maybe add a -r flag to reset?

**Comment by despiegk** [comment]
docker has no state right?
if you stop you loose the state.
we can add a check if it already is started then don't do anything & warn its started
and -r to reset indeed

**Comment by grimpy** [comment]
@despiegk a docker container can perfectly be stopped and started (in my case this was after a reboot)
