### ISSUE TITLE
js9_start fails with port is already allocated

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#47]
Here are the steps:
```
export GIGBRANCH="9.0.0"
export GIGSAFE=1
export GIGDIR="/Users/yves/gig9"
rm -rf $GIGDIR
rm -rf /tmp/jsinit.sh
curl https://raw.githubusercontent.com/Jumpscale/developer/${GIGBRANCH}/jsinit.sh?$RANDOM > /tmp/jsinit.sh
bash /tmp/jsinit.sh
source ~/.jsenv.sh
js9_build -l -p
js9_start
```

=> see `/tmp/install.log`:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint js9 (427b668fb3a235c00c70cb964e3fc6fb4d76ea2ff0189ef4e82dfbdc42211bf4): Bind for 0.0.0.0:2222 failed: port is already allocated.
```

When checking with `docker ps`:
```
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                  NAMES
2f58f7aff711        jumpscale/js9_base0   "/sbin/my_init"     About an hour ago   Up About an hour    0.0.0.0:2222->22/tcp   js9_base
```

Retrying with another port, executing `js9_start -p 2223`, again `something went wrong: docker could not start, please check /tmp/install.log`...

=> see `/tmp/install.log`:
```
Error response from daemon: driver failed programming external connectivity on endpoint js9 (317715c4cb1658d343da08e784439954a7dcf727760fb936ddba39b6f6a16938): Bind for 0.0.0.0:2222 failed: port is already allocated
Error: failed to start containers: js9
```

**Comment by yveskerwyn** [comment]
I had to manually stop the js9_base container, before I could run `js9_start`

Did we change behavior without updating the documentation?

**Comment by rkhamis** [comment]
It's starting `js9` instead of `js9_base`
So it didn't take your previous docker into consideration. Fix by removing this docker and using js9_start as normal. It will always restart the docker if stopped and recreate the docker if not previously created as expected.

or you can use `js9_start -n js9_base`

**Comment by rkhamis** [comment]
Added always clean base image first

**Comment by ahussein** [comment]
verified
