### ISSUE TITLE
js9_start: command not found

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#48]
After having executed `source ~/.jsenv.sh` in a new terminal session, `js9_start` is not found...

What can be cause of this? What to check?

![screen shot 2017-06-12 at 20 50 26](https://user-images.githubusercontent.com/13795109/27049845-d925f6c6-4fb0-11e7-89a5-fbb70f2c1597.png)

**Comment by rkhamis** [comment]
@yveskerwyn You need to reinstall.
Please follow the documentation and close when verified
