### ISSUE TITLE
jsinit.sh wrongly states that you need to execute js9_start -b

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#55]
After having executed `jsinit.sh` you get this:

![screen shot 2017-06-28 at 10 47 41](https://user-images.githubusercontent.com/13795109/27628450-5afb4382-5bef-11e7-9825-4ba3657129dc.png)

This is wrong since the next step is to execute:
```
source ~/.jsenv.sh
js9_build -l -p
```

Only when that is done you should execute `js9_start`

**Comment by arahmanhamdy** [comment]
@yveskerwyn the tip to run `source .jsenv.sh` has been fixed at the master:
https://github.com/Jumpscale/developer/commit/6064a5b4cceb13fa20d9662019ce09c830194fcf#diff-2f2fb797955222e3a32127e0afe07df3R207

the js9_start -b can be alternative to js9_build -l, it will install jumpscale libraries

**Comment by john-kheir** [comment]
js9_start -b doesn't build

**Comment by arahmanhamdy** [comment]
after removing -l by commit https://github.com/Jumpscale/developer/commit/6f677d7ca928ad05fd49f1a604f60e47f400cd5d#diff-649cb786c512db21cfa722f546ff0f1fL60 , the behavior intended for the installer now is : 

- js9_start -b (will build jumpscale9 image with core9 installed only and start a js9 container)
- js_build -l (will build jumpscale9 image with core9,lib9,ays9,prefab9 installed without portal)
- js_build -p (will build jumpscale9 image with core9,lib9,ays9,prefab9,portal9)
- js9_start (will create js9 container only if it found a docker image called jumpscale/base3 which was built by any of the three previous commands, note that it will delete any previous js9 container)

**Comment by ahmedelsayed-93** [comment]
### software version
 master : b469431
