### ISSUE TITLE
building js9 from 9.0.0 succeeds but referencing unexisting /dev/net/tun

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#57]
After having build successfully from 9.0.0 and started js9, executing the below reveals a reference to an unexisting `/dev/net/tun` device:

```
docker inspect js9 | grep -i net
"NetworkMode": "default",
                "NET_ADMIN",
                    "PathOnHost": "/dev/net/tun",
                    "PathInContainer": "/dev/net/tun",
```

When checking there's not directory for it:
```
(js9) $ ls /dev/net
ls: /dev/net: No such file or directory
```

**Comment by yveskerwyn** [comment]
This problem could be solved by adding the `--privileged` option to the `docker run` command in `js9_start`, but that didn't solved the problem as described in https://github.com/Jumpscale/developer/issues/61

**Comment by rkhamis** [comment]
@arahmanhamdy could you add the commit that solved it please? or add some info?

**Comment by arahmanhamdy** [comment]
The issue was related to docker permissions on mac
Commit: https://github.com/Jumpscale/developer/commit/2e8d52e27493d62a7a6e2f45f3f4115bf93a0c43
