### ISSUE TITLE
js9_start command not found in new terminal session

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#58]
After successfully having build and started js9 from the 9.0.0 branch, I open a new terminal session, and execute the following:
```
source ~/.jsenv.sh
js9_start
```

This results in:
```
-bash: js9_start: command not found
```

Is this by design?

If that's the case, how can I then use `js9_start` in a new terminal session?

**Comment by ahussein** [comment]
are you trying this on a Linux system ? if not then on which platform do you see this behavior ?

**Comment by yveskerwyn** [comment]
On Mac, but I figured out what is wrong...

Since I used `export GIGSAFE=1` I need to execute first again `export GIGDIR=...` before executing `source ~/.jsenv.sh` in my new terminal session
