### ISSUE TITLE
Installation to pull repos with explicit https as fallback

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#59]
As part of the `js9_build -l -p` script we should verify that the user has registered his SSH key into his GitHub account and if not give an error message explaining what the problem is.

Currently you simply get this:
```
...
Cloning into 'core9'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by grimpy** [comment]
You can test this with the follow command 
`git ls-remote git@github.com:jumpscale/core9`

**Comment by ahussein** [comment]
I am not sure why you want to give an error message. These are public repositories (unless there is a plan to  change that), so we first try to clone via ssh and if we fail we then try to use https which should work for anyone.

**Comment by rkhamis** [comment]
This case can only happen when:
1- repos are cloned with ssh on host machine
2- sshkey configured in github **ISN"T** added to ssh-agent during installation (as [documented](https://github.com/Jumpscale/developer/blob/master/README.md))

However, we're already adding a fallback to a badly installed system, that we STILL don't fail unless there are private repos.

**Comment by ahmedelsayed-93** [comment]
### software version
master : b469431
