### ISSUE TITLE
Send js9_start errors about non existing containers to /dev/null

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#60]
When removing the images in `js9_start`, send the errors to `/dev/null` in case the containers don't exist.

Now you get this:

![screen shot 2017-06-30 at 10 03 33](https://user-images.githubusercontent.com/13795109/27726824-3c18f282-5d7c-11e7-9e29-986eaf53f003.png)

**Comment by ahmedelsayed-93** [comment]
### software version
master : b469431
