### ISSUE TITLE
error while trying to initialise G8core client in JS 82

### ISSUE THREAD

**Issue by hofkensj** [Jumpscale/developer#7]
![screenshot from 2017-04-24 19-30-28](https://cloud.githubusercontent.com/assets/16613288/25350213/b6774678-2924-11e7-80e9-8464d3d6da4a.png)

environment:
JS installed with new developer env script - attached to zerotier network
G8OS running in virtual box - in same zero tier network

then executed in JS : cl = j.clients.g8core.get('ip @ of g8OS in zero tier network')

**Comment by FastGeert** [comment]
Is not a bug of the docker js installer but of js. Please file in the correct location.
