### ISSUE TITLE
When the ssh-agent and key are not loaded, no clear error message is shown

### ISSUE THREAD

**Issue by FastGeert** [Jumpscale/developer#74]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description
```
(js9) gig@gig-Lenovo-Yoga-2-Pro:~$ js9_build -lp
[+] will install: js9 libs
[+] will install: js9 portal
[+] start docker phusion/baseimage -> base0 (port:2222)
[+] authorizing local ssh keys on docker: base0
```

Nothing else is shown, the user thinks, all is ok, but nothing happened

**Comment by arahmanhamdy** [comment]
https://github.com/Jumpscale/developer/pull/77/commits/e020bd6bee97bb50c721029d32b2881fbfa493c9
