### ISSUE TITLE
Harmful purging of known hosts

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/developer#8]
when preparing the host.

In line: https://github.com/Jumpscale/developer/blob/master/jsinit.sh#L248

**Comment by despiegk** [comment]
why is that harmful?
its on a development machine

**Comment by zaibon** [comment]
They are cleaner way to do this then cleaning completely the file. 
only the specific IP of the docker should be removed, see : https://github.com/Jumpscale/developer/blob/refactor/scripts/js_builder82_zerotier.sh#L146
