### ISSUE TITLE
js9_start --- looking for jumpscale/base3

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/developer#82]
#### Installation information

- jumpscale version:
v9.1.1 (downloaded zip file)

- operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

#### Detailed description

The code fails to retrieve the right Docker Container.

```
bname=jumpscale/js9base3
```
It should be:

```
bname=jumpscale/base3
```

#### Steps to reproduce

Execute: __js9_start__

**Comment by rkhamis** [comment]
I just re-tested, and no. bname is correct.
Even on 9.1.1 it's `jumpscale/base3`. See: https://github.com/Jumpscale/developer/blob/9.1.1/scripts9/js_start_js9.sh#L13

**Comment by rainmanh** [comment]
@rkhamis , I have looked in docker hub: __https://hub.docker.com/r/jumpscale/__ and I have only found : __jumpscale/js9base3__
I cannot see __docker pull jumpscale/base3__ anywhere.

```
docker pull jumpscale/base3
Using default tag: latest
Pulling repository docker.io/jumpscale/base3
Error: image jumpscale/base3:latest not found
```

**Comment by rkhamis** [comment]
The `jumpscale/base3` image is one that is committed locally. If you follow the [README](https://github.com/Jumpscale/developer/blob/master/README.md), you'll have no issues

**Comment by rainmanh** [comment]
Apologies @rkhamis , to build first before running it!!!

Would be possible to amend the README with a couple of steps for clarity sake ?:

1. Build the Docker image
2. Start the Docker container

That was the part that confused me a bit.

Thanks for pointing this bit out.
