### ISSUE TITLE
Typo in README. md file

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/developer#84]
https://github.com/Jumpscale/developer/blob/master/README.md

It reads:
````
export $HOMEDIR=~ # 
````
when it should be:

````
export HOMEDIR=~ # 
````

**Comment by rainmanh** [comment]
@rkhamis , Can you please update the tickets when closing ?
The Community is very interested in having some feedback from development.

**Comment by rkhamis** [comment]
@rainmanh the commit that fixes it is referenced.

Thanks for the eagle eye!

**Comment by rainmanh** [comment]
Sorry mate!! I was looking somewhere else!
