### ISSUE TITLE
Errors, missing packagrs when starting JS9

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/developer#88]
#### Installation information

- jumpscale version: js9
- operating system: Ubuntu 16.04

<img width="747" alt="screen shot 2017-09-04 at 10 23 37" src="https://user-images.githubusercontent.com/13795109/30017915-36c1daf2-915b-11e7-9f0d-9b9c90582078.png">

**Comment by rkhamis** [comment]
This is by design. To use these clients, you'd install their corresponding modules.
