### ISSUE TITLE
Cleanify install to touch less possible the host and be more generic

### ISSUE THREAD

**Issue by maxux** [Jumpscale/developer#9]
IMO, it would be better to do nothing on the host, except creating a local directory (eg: `~/.local/cache/jumpscale`) and testing docker existence.

Run a docker which mount the local directory to `/opt` in the docker and do everything on that docker (`git clone`, `apt-get install stuff`, etc.)

With this workflow, you can remove a lot of os-specific stuff and not touch at all the host, even don't need to be root nor sudo (if your user is part of docker group). This would be a great security and proper improvement.

**Comment by despiegk** [comment]
i don't agree, there need to be some env variables e.g. the SSH-key you are going to use
also the way how we launch install commands, should be generic

**Comment by zaibon** [comment]
> the way how we launch install commands, should be generic

What commands are you revering to ? basic packages like `curl`, `python` and `git` ?

**Comment by rkhamis** [comment]
Done
